"""Initial editorial reference content. Seeded once by Alembic, never on startup."""
def article(slug, title, category, severity, summary, explanation, impact, mitigation, validation, limitations, reference_url, check_id=None):
    return dict(slug=slug, title=title, category=category, severity=severity, summary=summary,
        explanation=explanation, impact=impact, mitigation=mitigation, validation=validation,
        limitations=limitations, reference_url=reference_url,
        coverage='automated' if check_id else 'educational', check_ids=[check_id] if check_id else [], published=True)


ARTICLES = [
    article('tls-certificates', 'TLS certificates & protocol', 'Transport security', 'high',
        'Keep encrypted connections trusted, current, and compatible with modern TLS.',
        'TLS authenticates the server and encrypts traffic. Expired certificates, an untrusted certificate chain, or legacy protocol negotiation can prevent a trustworthy connection.',
        'Visitors may encounter certificate errors or use an obsolete transport protocol. A failed handshake can also be a connectivity issue rather than a confirmed cryptographic weakness.',
        'Install a certificate from a trusted CA and serve its intermediate chain.\nAutomate renewal and alert before expiry.\nDisable TLS 1.0 and 1.1; support TLS 1.2 and 1.3.',
        'Inspect the certificate chain and expiry in your browser. Re-run the scan after changing your edge or load balancer configuration.',
        'The scanner attempts one TLS handshake and checks the negotiated version and expiry. It does not enumerate all supported ciphers or prove every deprecated protocol is disabled.',
        'https://cheatsheetseries.owasp.org/cheatsheets/Transport_Layer_Security_Cheat_Sheet.html', 'TLS-01'),
    article('website-reachability', 'Website reachability', 'Transport security', 'info',
        'Understand why a target could not be reached before interpreting other results.',
        'When neither HTTPS nor HTTP responds, the scanner records a reachability failure. DNS, firewall rules, downtime, routing, or bot protection may be responsible.',
        'An unreachable target cannot be fully assessed. This observation alone does not prove an exploitable vulnerability.',
        'Check public DNS and service uptime.\nConfirm the web server accepts traffic on the intended ports.\nReview firewall and bot-protection logs before changing allowlists.',
        'Test the URL from an independent network and inspect server logs, then repeat the scan.',
        'Reachability is observed from the scanner’s network at a particular time, not a global availability guarantee.',
        'https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview', 'NET-00'),
    article('https-availability', 'HTTPS availability', 'Transport security', 'high',
        'Make your public website available over an encrypted transport.',
        'A site that is reachable only over HTTP sends traffic without TLS encryption. WevnSec attempts HTTPS before falling back to HTTP.',
        'A network observer may read or alter plaintext traffic, including information entered by visitors.',
        'Enable HTTPS with a trusted certificate.\nRemove mixed-content resource URLs.\nRedirect HTTP traffic after confirming HTTPS works.',
        'Open the HTTPS URL directly and confirm the page and resources load without certificate or mixed-content errors.',
        'The HTTP probe checks availability; certificate trust is assessed by the separate TLS check. HTTPS availability does not establish application security.',
        'https://developer.mozilla.org/en-US/docs/Web/Security/Transport_Layer_Security', 'NET-01'),
    article('https-redirects', 'HTTP to HTTPS redirects', 'Transport security', 'medium',
        'Send visitors from plaintext HTTP to HTTPS consistently.',
        'An HTTP endpoint should redirect to an HTTPS URL rather than serve the application over plaintext. The scanner checks the root response and Location header.',
        'Visitors following HTTP links may continue sending unencrypted requests.',
        'Configure an edge or web-server redirect to your intended HTTPS origin.\nPreserve the path and query.\nAvoid redirect loops and validate the destination host.',
        'Inspect the HTTP response headers for a 301, 302, 303, 307, or 308 response with the expected HTTPS Location.',
        'Only the root redirect is checked. A redirect alone does not prevent the first plaintext request; consider HSTS.',
        'https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections', 'NET-02'),
    article('hsts', 'HTTP Strict Transport Security', 'Security headers', 'high',
        'Tell browsers to use HTTPS for future visits.',
        'The Strict-Transport-Security header instructs supporting browsers to use HTTPS for a specified lifetime.',
        'Without HSTS, a visitor may attempt a plaintext connection before being redirected.',
        'Confirm all affected hosts support HTTPS first.\nRoll out Strict-Transport-Security with a short max-age, then increase it.\nUse includeSubDomains and preload only after evaluating every affected subdomain and preload requirements.',
        'Inspect the HTTPS response header and validate its directives. Test representative subdomains before broadening the policy.',
        'WevnSec currently checks header presence, not directive correctness, preload registration, or every response path.',
        'https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security', 'HDR-strict'),
    article('content-security-policy', 'Content Security Policy', 'Security headers', 'medium',
        'Limit the sources and behaviors your pages may load or execute.',
        'CSP is a browser policy that can restrict scripts, frames, connections, and other resource types. A well-designed policy reduces the impact of some injection vulnerabilities.',
        'Missing or overly permissive policies remove a defense-in-depth layer. A missing header is not proof of XSS.',
        'Inventory resource origins and begin with a report-only policy.\nPrefer script nonces or hashes and avoid unsafe-inline and unsafe-eval where possible.\nRestrict object-src and base-uri, and configure frame-ancestors for your embedding needs.',
        'Review browser violation reports and exercise key user flows before enforcing the policy.',
        'The scanner checks for the header only. It does not evaluate policy strength or test for script injection.',
        'https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html', 'HDR-conten'),
    article('clickjacking', 'Clickjacking protection', 'Security headers', 'medium',
        'Control which sites can embed your pages in a frame.',
        'Clickjacking hides or disguises an interactive page inside another site. X-Frame-Options and CSP frame-ancestors can limit embedding.',
        'A visitor may be tricked into clicking a sensitive action on your application.',
        'Set CSP frame-ancestors to the precise allowed origins or none.\nWhere appropriate, also use X-Frame-Options: DENY or SAMEORIGIN.\nKeep intentional third-party embedding requirements in mind.',
        'Try embedding a sensitive page from an unauthorized origin and confirm the browser blocks it.',
        'The current automated check looks for X-Frame-Options. A site using only CSP frame-ancestors may be flagged even when framing is appropriately restricted.',
        'https://cheatsheetseries.owasp.org/cheatsheets/Clickjacking_Defense_Cheat_Sheet.html', 'HDR-x-fram'),
    article('mime-sniffing', 'MIME sniffing protection', 'Security headers', 'low',
        'Prevent browsers from treating a resource as an unexpected content type.',
        'X-Content-Type-Options: nosniff tells browsers to honor declared MIME types in supported contexts.',
        'Incorrectly served user-controlled files may be interpreted as active content.',
        'Serve correct Content-Type values.\nAdd X-Content-Type-Options: nosniff.\nServe untrusted downloads with appropriate Content-Disposition and consider a separate origin.',
        'Inspect response headers for representative HTML, scripts, styles, and uploaded files.',
        'The scanner checks the presence of the header at the root, not its value or every uploaded resource.',
        'https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options', 'HDR-x-cont'),
    article('referrer-policy', 'Referrer policy', 'Security headers', 'low',
        'Reduce accidental disclosure of page URLs to other origins.',
        'Referrer-Policy controls the Referer information browsers include on outgoing requests.',
        'Paths or query parameters containing sensitive identifiers may be disclosed by overly permissive policies.',
        'Choose a policy such as strict-origin-when-cross-origin or no-referrer based on your application.\nDo not place credentials or sensitive secrets in URLs.',
        'Inspect cross-origin requests in browser developer tools and confirm only the intended information is sent.',
        'Modern browsers have defaults. Missing an explicit header does not necessarily mean full URLs are leaked; the scanner does not evaluate effective browser behavior.',
        'https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy', 'HDR-referr'),
    article('permissions-policy', 'Browser permissions policy', 'Security headers', 'low',
        'Restrict access to browser features your site does not need.',
        'Permissions-Policy can limit features such as camera, microphone, and geolocation for documents and embedded frames.',
        'Unnecessarily available features can increase the impact of compromised or untrusted embedded content.',
        'Inventory required browser capabilities.\nDisable unused features and permit only intended origins for enabled features.\nTest embedded flows after changes.',
        'Inspect the response policy and browser console, then exercise flows needing restricted features.',
        'Header presence is checked, not policy completeness or browser-specific enforcement. Support varies by feature and browser.',
        'https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy', 'HDR-permis'),
    article('server-fingerprints', 'Server fingerprint disclosure', 'Information disclosure', 'low',
        'Avoid unnecessary software and version details in response headers.',
        'Server and X-Powered-By headers may expose implementation details. WevnSec reports their presence as an observation.',
        'Version information can help an attacker prioritize known weaknesses, but hiding it is not a replacement for patching.',
        'Remove unnecessary X-Powered-By headers.\nSuppress detailed server version banners where supported.\nKeep components patched regardless of exposed metadata.',
        'Inspect response headers at the edge, not just the application server.',
        'A generic banner can be harmless. The scanner does not map disclosed versions to a live CVE database.',
        'https://owasp.org/www-project-web-security-testing-guide/', 'HDR-SRV'),
    article('cookie-flags', 'Cookie security flags', 'Session security', 'medium',
        'Apply appropriate Secure, HttpOnly, and SameSite attributes to cookies.',
        'Cookie attributes restrict transport, script access, and cross-site sending. Session cookies typically need stricter handling than non-sensitive preferences.',
        'Weak session cookie handling can increase exposure to interception, script access, or cross-site requests.',
        'Use Secure on HTTPS cookies.\nUse HttpOnly for session cookies that do not need JavaScript access.\nChoose SameSite=Lax or Strict where compatible; SameSite=None requires Secure.\nSet deliberate lifetime, path, and domain restrictions.',
        'Inspect Set-Cookie responses during login and privileged workflows, not just the homepage.',
        'The scan inspects root-page Set-Cookie headers with a heuristic. It does not authenticate, classify cookie sensitivity, or test session invalidation.',
        'https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html', 'CK-01'),
    article('cors', 'Cross-origin resource sharing', 'Access control', 'high',
        'Expose browser-readable cross-origin responses only where intended.',
        'CORS determines whether another origin’s scripts may read a response. WevnSec sends an arbitrary Origin and checks whether it is reflected or wildcarded.',
        'Overly broad CORS on sensitive responses can expose data in some authentication and credential configurations.',
        'Allowlist trusted origins for sensitive endpoints.\nAvoid blindly reflecting Origin.\nUse credentialed CORS only where necessary and return Vary: Origin for origin-specific responses.',
        'Test sensitive endpoints from authorized and unauthorized browser origins with the actual authentication mode.',
        'Wildcard CORS can be intentional for a public API. A root-page observation does not prove sensitive data exposure or credentialed exploitation.',
        'https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS', 'CORS-01'),
    article('exposed-configuration', 'Exposed secrets & configuration', 'Information disclosure', 'critical',
        'Keep environment files, repositories, and deployment configuration outside your public webroot.',
        'The ownership-gated advanced scan probes a bounded set of sensitive paths including .env and .git files and compares responses with a random-path baseline.',
        'An exposed file can reveal credentials or internal details. A successful HTTP response alone is not conclusive proof of a leaked secret.',
        'Remove sensitive files from publicly served directories.\nDeny dotfile access at the edge while preserving intentional .well-known resources.\nIf credentials were exposed, rotate them and inspect access logs; deleting the file alone is not enough.',
        'Verify that affected paths no longer return sensitive content from an unauthenticated session. Review suspected matches manually.',
        'This is a status/size heuristic, not content-based secret confirmation. SPA catch-all pages and custom error pages can produce false positives or negatives. Verified ownership is required.',
        'https://cheatsheetseries.owasp.org/cheatsheets/Secrets_Management_Cheat_Sheet.html', 'LEAK-01'),
]

REFERENCE_TOPICS = [
    ('cross-site-scripting', 'Cross-site scripting (XSS)', 'Injection', 'high',
     'Untrusted data reaches an HTML, JavaScript, or DOM execution context.',
     'An attacker may execute script in a visitor’s session, read exposed data, or perform actions as that visitor.',
     'Use context-aware output encoding.\nPrefer safe text APIs over HTML injection.\nSanitize intentionally allowed HTML with a maintained sanitizer.\nTreat CSP as defense in depth, not the primary fix.',
     'Review untrusted inputs and their output contexts. Test in an authorized environment with application-specific cases.', 'Cross_Site_Scripting_Prevention'),
    ('sql-injection', 'SQL injection', 'Injection', 'critical',
     'Application input is concatenated into SQL syntax rather than bound as a value.',
     'An attacker may read or modify database contents, depending on the query and database privileges.',
     'Use parameterized queries or safely bound ORM expressions.\nAllowlist identifiers that cannot be parameterized.\nUse least-privilege database roles; escaping alone is not the preferred defense.',
     'Review every query construction path and add regression tests for untrusted inputs in a controlled environment.', 'SQL_Injection_Prevention'),
    ('broken-object-authorization', 'Broken object authorization (IDOR)', 'Access control', 'high',
     'An endpoint accepts an object identifier without checking whether the caller is allowed to access that object.',
     'Users may read or alter another account’s records, even when identifiers are hard to guess.',
     'Enforce server-side authorization for each object and operation.\nScope database queries to the authenticated principal or tenant.\nTest both horizontal and vertical privilege boundaries.',
     'Use two authorized test accounts and verify that object IDs cannot be exchanged to gain access.', 'Insecure_Direct_Object_Reference_Prevention'),
    ('server-side-request-forgery', 'Server-side request forgery (SSRF)', 'Request handling', 'high',
     'User-controlled input influences a server-side network request to an unintended destination.',
     'The server may reach internal services, metadata endpoints, or protected networks on an attacker’s behalf.',
     'Prefer strict destination allowlists.\nValidate schemes, hosts, ports, DNS results, and every redirect.\nPrevent DNS rebinding and restrict network egress.\nDo not forward sensitive headers across origins.',
     'Test destination handling using controlled endpoints and inspect egress controls without probing unauthorized networks.', 'Server_Side_Request_Forgery_Prevention'),
    ('cross-site-request-forgery', 'Cross-site request forgery (CSRF)', 'Session security', 'high',
     'A browser sends an unwanted state-changing request using credentials attached automatically, such as cookies.',
     'A visitor may unintentionally perform a privileged action on a site where they are signed in.',
     'Use CSRF tokens on state-changing cookie-authenticated requests.\nValidate Origin where appropriate and use SameSite cookies as defense in depth.\nDo not make GET requests change state.',
     'Test cross-origin forms and fetches against a controlled account and confirm unauthorized changes are rejected.', 'Cross-Site_Request_Forgery_Prevention'),
    ('vulnerable-dependencies', 'Vulnerable dependencies', 'Supply chain', 'high',
     'Third-party components can introduce known weaknesses into your application.',
     'Impact depends on the vulnerable component, its version, and whether the vulnerable functionality is reachable.',
     'Maintain an inventory and lockfiles.\nUse software composition analysis and review advisories.\nPrioritize exploitable issues, upgrade safely, and regression-test changes.',
     'Run dependency analysis against the actual build and confirm remediation in the deployed artifact.', 'Vulnerable_Dependency_Management'),
    ('authentication-hardening', 'Authentication hardening', 'Session security', 'high',
     'Authentication can fail through weak credential handling, recovery flows, session management, or missing abuse controls.',
     'Attackers may impersonate users or maintain access after a session should have ended.',
     'Use proven authentication libraries, secure password storage, and MFA where appropriate.\nRate-limit sensitive authentication actions.\nProtect recovery flows and invalidate sessions deliberately.',
     'Review login, recovery, MFA, and logout as separate flows using authorized test accounts.', 'Authentication'),
    ('insecure-deserialization', 'Insecure deserialization', 'Injection', 'critical',
     'An application converts untrusted serialized data into unsafe executable objects or privileged state.',
     'Depending on the format and runtime, this may allow state tampering, denial of service, or code execution.',
     'Use simple schema-validated data formats for untrusted inputs.\nAvoid native object deserialization of untrusted content.\nConstrain types and sizes and maintain runtime dependencies.',
     'Review serialization boundaries and test rejection of unexpected types and oversized data without executing unsafe payloads.', 'Deserialization'),
]
for slug, title, category, severity, explanation, impact, mitigation, validation, reference in REFERENCE_TOPICS:
    ARTICLES.append(article(slug, title, category, severity, explanation, explanation, impact, mitigation, validation,
        'Reference only. The current WevnSec automated scanner does not detect or rule out this vulnerability. Application-specific review or an authorized manual assessment is needed.',
        f'https://cheatsheetseries.owasp.org/cheatsheets/{reference}_Cheat_Sheet.html'))