import { Link } from "react-router-dom";
import { Bell, CheckCheck, ArrowUpRight, History } from "lucide-react";
import { Grade, issueCount, ago, ReportActions } from "./shared";

export const HistoryList = ({history}) => <section className="dash-section" data-testid="scan-history-section">
    <div className="dash-section-heading"><h2><History size={17}/>Scan history</h2><span className="dash-subtle" data-testid="history-limit">Latest {history.length} scans · up to 50</span></div>
    {!history.length ? <div className="dash-empty" data-testid="history-empty"><History size={27}/><h3>No scans found</h3><p>Your signed-in scans will appear here.</p></div> : <div className="dash-history-list">{history.map((s,i) => <div className="dash-history-row" key={s.share_id} data-testid={`history-row-${i}`}><Grade grade={s.grade} testId={`history-grade-${s.share_id}`}/><Link data-testid={`history-report-${s.share_id}`} to={`/report/${s.share_id}`} className="dash-history-target"><strong>{s.target}</strong><small>{new Date(s.created_at).toLocaleString()}</small></Link><span className="dash-history-score" data-testid={`history-score-${s.share_id}`}>{s.score}<small>/100</small></span><span className="dash-subtle" data-testid={`history-findings-${s.share_id}`}>{issueCount(s)} findings</span><span className="dash-source" data-testid={`history-source-${s.share_id}`}>{s.source === "scheduled" ? "Scheduled" : "Manual"}</span><div className="dash-row-actions"><ReportActions scan={s} prefix={`history-${s.share_id}`}/></div></div>)}</div>}
</section>;

const EMAIL_STATUS = {sent:"Email accepted by provider",pending:"Email queued",retrying:"Email retry scheduled",sending:"Sending email",disabled:"Email alerts off",failed:"Email failed",uncertain:"Delivery unconfirmed"};
export const AlertList = ({alerts, onRead}) => <section className="dash-section" data-testid="dashboard-alerts">
    <div className="dash-section-heading"><h2><Bell size={17}/>Drift inbox</h2><span className="dash-subtle">Grade declines</span></div>
    {!alerts.length ? <div className="dash-empty" data-testid="alerts-empty"><CheckCheck size={29}/><h3>No grade drops recorded</h3><p>Your drift inbox is clear.</p></div> : <div>{alerts.map(a => <article className={`dash-alert ${a.read ? "is-read" : ""}`} data-testid={`drift-alert-${a.id}`} key={a.id}><span className="dash-alert-icon"><Bell size={18}/></span><div className="dash-alert-body"><div><strong data-testid={`alert-domain-${a.id}`}>{a.domain}</strong><span className="dash-subtle">{ago(a.created_at)}</span></div><p data-testid={`alert-grade-drop-${a.id}`}>{a.previous_grade || "Previous grade"} <span>→</span> {a.current_grade || "Lower grade"} <small>{a.previous_score} → {a.current_score}/100</small></p><small data-testid={`alert-email-status-${a.id}`} className={['failed','uncertain'].includes(a.email_status) ? "dash-error" : "dash-subtle"}>{EMAIL_STATUS[a.email_status] || a.email_status}</small>{a.email_error && <p className="dash-error" data-testid={`alert-email-error-${a.id}`}>{a.email_error}</p>}</div><div className="dash-alert-actions"><Link to={`/report/${a.scan_share_id}`} className="dash-text-link" data-testid={`alert-report-${a.id}`}>View report <ArrowUpRight size={14}/></Link>{!a.read && <button className="dash-icon-button" onClick={() => onRead(a.id)} title="Mark as read" aria-label={`Mark ${a.domain} alert as read`} data-testid={`alert-read-${a.id}`}><CheckCheck size={17}/></button>}</div></article>)}</div>}
</section>;