"""wevnsec schema

Revision ID: 9aa95ee97a93
Revises: 
Create Date: 2026-09-24 07:17:58.865901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9aa95ee97a93'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS wevnsec")
    op.create_table('profiles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='wevnsec'
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('scan_share_id', sa.String(length=16), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['wevnsec.profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='wevnsec'
    )
    op.create_index(op.f('ix_wevnsec_alerts_user_id'), 'alerts', ['user_id'], unique=False, schema='wevnsec')
    op.create_table('domains',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['wevnsec.profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'domain', name='uq_domains_user_domain'),
    schema='wevnsec'
    )
    op.create_index(op.f('ix_wevnsec_domains_user_id'), 'domains', ['user_id'], unique=False, schema='wevnsec')
    op.create_table('scans',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('share_id', sa.String(length=16), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=4), nullable=False),
    sa.Column('counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['wevnsec.profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='wevnsec'
    )
    op.create_index(op.f('ix_wevnsec_scans_created_at'), 'scans', ['created_at'], unique=False, schema='wevnsec')
    op.create_index(op.f('ix_wevnsec_scans_share_id'), 'scans', ['share_id'], unique=True, schema='wevnsec')
    op.create_index(op.f('ix_wevnsec_scans_user_id'), 'scans', ['user_id'], unique=False, schema='wevnsec')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wevnsec_scans_user_id'), table_name='scans', schema='wevnsec')
    op.drop_index(op.f('ix_wevnsec_scans_share_id'), table_name='scans', schema='wevnsec')
    op.drop_index(op.f('ix_wevnsec_scans_created_at'), table_name='scans', schema='wevnsec')
    op.drop_table('scans', schema='wevnsec')
    op.drop_index(op.f('ix_wevnsec_domains_user_id'), table_name='domains', schema='wevnsec')
    op.drop_table('domains', schema='wevnsec')
    op.drop_index(op.f('ix_wevnsec_alerts_user_id'), table_name='alerts', schema='wevnsec')
    op.drop_table('alerts', schema='wevnsec')
    op.drop_table('profiles', schema='wevnsec')
    # ### end Alembic commands ###
