import { useState } from "react";
import { Link } from "react-router-dom";
import useSWR, {mutate} from "swr";
import { Plus, Pencil, Trash2, Loader2, ArrowLeft, Search } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { AdminGate, CoverageBadge } from "@/components/docs/shared";
import { api, formatApiErrorDetail } from "@/lib/api";
import "@/components/docs/docs.css";

export default function DocumentationManager(){return <AdminGate><Manager/></AdminGate>;}
const Manager=()=>{
    const {data,error,isLoading,mutate:refresh}=useSWR("/admin/docs",url=>api.get(url).then(r=>r.data));
    const [query,setQuery]=useState(""),[removing,setRemoving]=useState(null),[busy,setBusy]=useState(false);
    const remove=async()=>{setBusy(true);try{await api.delete(`/admin/docs/${removing.id}`);setRemoving(null);await refresh();mutate("/docs");mutate("/stats");toast.success("Article removed");}catch(e){toast.error(formatApiErrorDetail(e.response?.data?.detail));}finally{setBusy(false);}};
    return <main className="docs-page" data-testid="docs-manager-page"><div className="docs-container"><Link to="/docs" className="docs-back" data-testid="manager-back-link"><ArrowLeft size={14}/>Public library</Link><div className="docs-manager-heading"><div><span className="docs-eyebrow" data-testid="manager-eyebrow">EDITORIAL WORKSPACE</span><h1 data-testid="manager-heading">Documentation</h1><p data-testid="manager-description">Published guidance and work in progress.</p></div><Button asChild data-testid="docs-new-article"><Link to="/docs/manage/new" data-testid="docs-new-article-link"><Plus size={15}/>New article</Link></Button></div>
        <label className="docs-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search all articles…" aria-label="Search managed articles" data-testid="manager-search"/></label>
        {isLoading ? <div className="docs-loading" data-testid="manager-loading"><Loader2 className="animate-spin"/>Loading articles…</div> : error ? <div className="docs-empty" data-testid="manager-error" role="alert">Unable to load articles.<button onClick={()=>refresh()} data-testid="manager-retry">Try again</button></div> : <div className="docs-manager-list">{data.filter(a=>`${a.title} ${a.category} ${a.slug}`.toLowerCase().includes(query.toLowerCase())).map(a=><div key={a.id} className="docs-manager-row" data-testid={`manager-row-${a.slug}`}><div><strong data-testid={`manager-title-${a.slug}`}>{a.title}</strong><small data-testid={`manager-date-${a.slug}`}>{a.category} · Updated {new Date(a.updated_at).toLocaleDateString()}</small></div><CoverageBadge article={a} testId={`manager-coverage-${a.slug}`}/><span className={`docs-publication ${a.published ? "published" : ""}`} data-testid={`manager-status-${a.slug}`}>{a.published ? "Published" : "Draft"}</span><div className="docs-manager-actions"><Link to={`/docs/manage/${a.id}`} title={`Edit ${a.title}`} aria-label={`Edit ${a.title}`} data-testid={`manager-edit-${a.slug}`}><Pencil size={15}/></Link><button onClick={()=>setRemoving(a)} aria-label={`Delete ${a.title}`} title={`Delete ${a.title}`} data-testid={`manager-delete-${a.slug}`}><Trash2 size={15}/></button></div></div>)}{!data.filter(a=>`${a.title} ${a.category} ${a.slug}`.toLowerCase().includes(query.toLowerCase())).length && <div className="docs-empty" data-testid="manager-empty">No matching articles.</div>}</div>}
        <Dialog open={Boolean(removing)} onOpenChange={open=>{if(!open&&!busy)setRemoving(null);}}><DialogContent data-testid="delete-article-dialog"><DialogHeader><DialogTitle data-testid="delete-article-title">Delete this article?</DialogTitle><DialogDescription data-testid="delete-article-description">“{removing?.title}” will be removed from the library. This cannot be undone. Scan reports will not be deleted.</DialogDescription></DialogHeader><div className="flex justify-end gap-3"><Button variant="outline" disabled={busy} onClick={()=>setRemoving(null)} data-testid="delete-article-cancel">Cancel</Button><Button variant="destructive" disabled={busy} onClick={remove} data-testid="delete-article-confirm">{busy ? <Loader2 size={15} className="animate-spin"/> : <Trash2 size={15}/>}Delete article</Button></div></DialogContent></Dialog>
    </div></main>;
};