import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import useSWR, {mutate} from "swr";
import { ArrowLeft, Loader2, Save, Eye, AlertTriangle } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { AdminGate } from "@/components/docs/shared";
import { api, formatApiErrorDetail } from "@/lib/api";
import "@/components/docs/docs.css";

const EMPTY={title:"",slug:"",summary:"",category:"",severity:"medium",coverage:"educational",check_ids:[],explanation:"",impact:"",mitigation:"",validation:"",limitations:"",reference_url:"",published:false};
const PROSE=[["explanation","What it means",10,20000],["impact","Why it matters",5,10000],["mitigation","How to address it",10,20000],["validation","Validate your changes",5,10000],["limitations","Scope and limitations",5,10000]];
export default function DocumentationEditor(){return <AdminGate><Editor/></AdminGate>;}
const Editor=()=>{
    const {id}=useParams(),navigate=useNavigate(),isNew=!id;
    const {data:catalog=[]}=useSWR("/docs/catalog",url=>api.get(url).then(r=>r.data));
    const [form,setForm]=useState(EMPTY),[loading,setLoading]=useState(!isNew),[busy,setBusy]=useState(false),[error,setError]=useState(null),[dirty,setDirty]=useState(false),[loadVersion,setLoadVersion]=useState(0);
    const [slugTouched,setSlugTouched]=useState(false);
    useEffect(()=>{if(!id)return;let active=true;setLoading(true);setError(null);api.get(`/admin/docs/${id}`).then(({data})=>{if(active){setForm(Object.fromEntries([...Object.keys(EMPTY),"version"].map(k=>[k,data[k]])));setDirty(false);}}).catch(e=>{if(active)setError(formatApiErrorDetail(e.response?.data?.detail));}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[id,loadVersion]);
    useEffect(()=>{if(!dirty)return;const warn=e=>{e.preventDefault();e.returnValue="";};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[dirty]);
    const change=(key,value)=>{setForm(f=>({...f,[key]:value,...(key==="coverage"&&value==="educational" ? {check_ids:[]} : {})}));setDirty(true);};
    const save=async e=>{e.preventDefault();setBusy(true);setError(null);try{const {data}=isNew ? await api.post("/admin/docs",form) : await api.put(`/admin/docs/${id}`,form);setDirty(false);mutate("/docs");mutate("/admin/docs");mutate("/stats");mutate(`/docs/${data.slug}`);toast.success(data.published ? "Article published" : "Draft saved");navigate("/docs/manage");}catch(e){setError(formatApiErrorDetail(e.response?.data?.detail));}finally{setBusy(false);}};
    const leave=e=>{if(dirty&&!window.confirm("Discard your unsaved changes?"))e.preventDefault();};
    return <main className="docs-page" data-testid="docs-editor-page"><div className="docs-container docs-editor-container"><Link to="/docs/manage" onClick={leave} className="docs-back" data-testid="editor-back-link"><ArrowLeft size={14}/>Manage documentation</Link><header className="docs-manager-heading"><div><span className="docs-eyebrow" data-testid="editor-eyebrow">EDITORIAL WORKSPACE</span><h1 data-testid="editor-heading">{isNew ? "New article" : "Edit article"}</h1></div>{!isNew && form.published && <Link to={`/docs/${form.slug}`} className="docs-manage-link" onClick={leave} data-testid="editor-view-public"><Eye size={15}/>View published article</Link>}</header>
        {loading ? <div className="docs-loading" data-testid="editor-loading"><Loader2 className="animate-spin"/>Loading article…</div> : <form onSubmit={save} className="docs-editor-form" data-testid="docs-editor-form">
            {error && <div role="alert" className="docs-editor-error" data-testid="editor-error"><AlertTriangle size={16}/><span>{error}</span>{!isNew && <button type="button" onClick={()=>{if(!dirty||window.confirm("Reload and discard unsaved changes?"))setLoadVersion(v=>v+1);}} data-testid="editor-reload">Reload article</button>}</div>}
            <div className="docs-editor-grid"><label className="docs-field" data-testid="editor-title-label">Title<input value={form.title} onChange={e=>{const value=e.target.value;change("title",value);if(isNew&&!slugTouched)change("slug",value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""));}} required minLength={3} maxLength={180} disabled={busy} data-testid="editor-title"/></label><label className="docs-field" data-testid="editor-slug-label">URL slug<input value={form.slug} onChange={e=>{setSlugTouched(true);change("slug",e.target.value);}} required maxLength={120} pattern="[a-z0-9]+(-[a-z0-9]+)*" disabled={busy} data-testid="editor-slug"/><small data-testid="editor-slug-help">Lowercase letters, numbers, and hyphens. Changing this changes the article URL.</small></label></div>
            <label className="docs-field" data-testid="editor-summary-label">Summary<textarea value={form.summary} onChange={e=>change("summary",e.target.value)} required minLength={10} maxLength={600} rows={3} disabled={busy} data-testid="editor-summary"/></label>
            <div className="docs-editor-grid"><label className="docs-field" data-testid="editor-category-label">Category<input value={form.category} onChange={e=>change("category",e.target.value)} required minLength={2} maxLength={80} list="doc-categories" disabled={busy} data-testid="editor-category"/><datalist id="doc-categories">{["Security headers","Transport security","Access control","Injection","Session security","Information disclosure","Supply chain","Request handling"].map(v=><option key={v} value={v}/>)}</datalist></label><label className="docs-field" data-testid="editor-severity-label">Reference severity<select value={form.severity} onChange={e=>change("severity",e.target.value)} disabled={busy} data-testid="editor-severity">{["info","low","medium","high","critical"].map(v=><option key={v} value={v}>{v[0].toUpperCase()+v.slice(1)}</option>)}</select></label></div>
            <div className="docs-editor-coverage"><label className="docs-field" data-testid="editor-coverage-label">Coverage<select value={form.coverage} onChange={e=>change("coverage",e.target.value)} disabled={busy} data-testid="editor-coverage"><option value="educational">Reference only — not detected by the scanner</option><option value="automated">Automated — linked to an implemented check</option></select></label>{form.coverage==="automated" && <fieldset className="docs-check-picker"><legend data-testid="editor-checks-legend">Related scanner checks (select at least one)</legend>{catalog.map(c=><label key={c.id} data-testid={`editor-check-label-${c.id}`}><input type="checkbox" checked={form.check_ids.includes(c.id)} onChange={e=>change("check_ids",e.target.checked ? [...form.check_ids,c.id] : form.check_ids.filter(v=>v!==c.id))} disabled={busy} data-testid={`editor-check-${c.id}`}/><span>{c.title}<small>{c.id} · {c.mode==="advanced" ? "Verified ownership required" : "Instant Scan"}</small></span></label>)}</fieldset>}</div>
            {PROSE.map(([key,label,min,max])=><label key={key} className="docs-field" data-testid={`editor-${key}-label`}>{label}<textarea rows={key==="mitigation" ? 7 : 5} value={form[key]} onChange={e=>change(key,e.target.value)} required minLength={min} maxLength={max} disabled={busy} data-testid={`editor-${key}`}/></label>)}
            <label className="docs-field" data-testid="editor-reference-label">Further reading URL (optional)<input type="url" value={form.reference_url} onChange={e=>change("reference_url",e.target.value)} placeholder="https://…" maxLength={2000} disabled={busy} data-testid="editor-reference"/></label>
            <div className="docs-editor-footer"><label className="docs-publish-switch" htmlFor="doc-published" data-testid="editor-publication-label"><Switch id="doc-published" checked={form.published} onCheckedChange={value=>change("published",value)} disabled={busy} data-testid="editor-published"/><span>{form.published ? "Publish to the public library" : "Save as private draft"}</span></label><Button type="submit" disabled={busy || (form.coverage==="automated"&&!form.check_ids.length)} data-testid="editor-save">{busy ? <Loader2 size={15} className="animate-spin"/> : <Save size={15}/>} {busy ? "Saving…" : form.published ? "Save & publish" : "Save draft"}</Button></div>
        </form>}
    </div></main>;
};